# Makefile for Exercise 5.20 - Expand dcl to handle function argument types & qualifiers

CC = gcc
CFLAGS = -Wall -Wextra -std=c99

TARGET = ex-5.20

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm -f $(TARGET)
