CC = gcc

# Source and Output
SRC = ex-1.2.c
OUT = ex-1.2

# Default target
all: build run

# Compile the program
build:
	$(CC) $(SRC) -o $(OUT)

# Run the program
run:
	./$(OUT)

# Clean the compiled files
clean:
	del $(OUT).exe